In [1]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Requirement already up-to-date: sklearn in c:\users\bjros\anaconda3\envs\pythondata\lib\site-packages (0.0)


Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


In [3]:
import pandas as pd

# Read the CSV and Perform Basic Data Cleaning

In [4]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1  FALSE POSITIVE              0              1              0              0   
2  FALSE POSITIVE              0              1              0              0   
3       CONFIRMED              0              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4    4.134435     1.050000e-05    -1.050000e-05   172.979370   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.003520  ...             -81      4.467           0.064   
1          0.000581  ...            -176      4.544           0.044   
2          0.000115  ...            -174      4.564           0.053   
3          0.001130  ...            -211      4.438           0.070   
4          0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 41 columns]

# Select your features (columns)

In [5]:
#Import Set Features Module
from sklearn.feature_selection import RFECV

# Set features. This will also be used as your x values.
selected_features = df.drop(['koi_disposition', 'koi_duration', 
                             'koi_time0bk_err2', 'koi_time0bk_err1', 'koi_period', 'koi_period_err1', 'koi_period_err2', 
                             'koi_srad_err1', 'dec', 'koi_impact_err1', 'koi_srad_err2', 'koi_impact', 'koi_srad', 
                             'koi_time0bk', 'koi_kepmag', 'koi_insol_err1', 'koi_prad_err1', 'koi_insol', 'koi_prad', 
                             'koi_prad_err2', 'koi_insol_err2', 'koi_depth_err1', 'koi_depth_err2', 'koi_impact_err2'], 
                            axis=1)
selected_features

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0                 0              0              0              0   
1                 0              1              0              0   
2                 0              1              0              0   
3                 0              0              0              0   
4                 0              0              0              0   
...             ...            ...            ...            ...   
6986              0              0              0              1   
6987              0              1              1              0   
6988              0              0              0              0   
6989              0              0              1              0   
6990              0              0              1              1   

      koi_duration_err1  koi_duration_err2  koi_depth  koi_teq  koi_model_snr  \
0               0.11600           -0.11600      874.8      443           25.8   
1               0.03410           -0.03410    10829.0      638           76.3   
2               0.00537           -0.00537     8079.2     1395          505.6   
3               0.04200           -0.04200      603.3     1406           40.9   
4               0.06730           -0.06730      686.0     1160           40.2   
...                 ...                ...        ...      ...            ...   
6986            0.63400           -0.63400       87.7      929            8.4   
6987            0.01740           -0.01740     1579.2     2088          453.3   
6988            0.22900           -0.22900       48.5     1608           10.6   
6989            0.16200           -0.16200      103.6     2218           12.3   
6990            0.28300           -0.28300       76.7     1266            8.2   

      koi_tce_plnt_num  koi_steff  koi_steff_err1  koi_steff_err2  koi_slogg  \
0                    2       5455              81             -81      4.467   
1                    1       5853             158            -176      4.544   
2                    1       5805             157            -174      4.564   
3                    1       6031             169            -211      4.438   
4                    2       6046             189            -232      4.486   
...                ...        ...             ...             ...        ...   
6986                 1       5638             169            -152      4.296   
6987                 1       5638             139            -166      4.529   
6988                 1       6119             165            -220      4.444   
6989                 1       6173             193            -236      4.447   
6990                 1       6469             158            -225      4.385   

      koi_slogg_err1  koi_slogg_err2         ra  
0              0.064          -0.096  291.93423  
1              0.044          -0.176  297.00482  
2              0.053          -0.168  285.53461  
3              0.070          -0.210  288.75488  
4              0.054          -0.229  296.28613  
...              ...             ...        ...  
6986           0.231          -0.189  298.74921  
6987           0.035          -0.196  297.18875  
6988           0.056          -0.224  286.50937  
6989           0.056          -0.224  294.16489  
6990           0.054          -0.216  297.00977  

[6991 rows x 17 columns]

# Create a Train Test Split

Use `koi_disposition` for the y values

In [6]:
koi_disposition = df['koi_disposition']
koi_disposition

0            CONFIRMED
1       FALSE POSITIVE
2       FALSE POSITIVE
3            CONFIRMED
4            CONFIRMED
             ...      
6986    FALSE POSITIVE
6987    FALSE POSITIVE
6988         CANDIDATE
6989    FALSE POSITIVE
6990    FALSE POSITIVE
Name: koi_disposition, Length: 6991, dtype: object

In [7]:
#Find the Shape of the Inputs & Outputs

koi_disposition = koi_disposition.values.reshape(-1,1)
print(f"Selected Features Shape: {selected_features.shape}")
print(f"koi_disposition Shape: {koi_disposition.shape}")

Selected Features Shape: (6991, 17)
koi_disposition Shape: (6991, 1)


In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(selected_features, koi_disposition, random_state=42)

In [9]:
X_train.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
6122              0              0              0              0   
6370              0              1              0              1   
2879              1              0              0              0   
107               0              0              0              0   
29                0              0              0              0   

      koi_duration_err1  koi_duration_err2  koi_depth  koi_teq  koi_model_snr  \
6122             0.3060            -0.3060      123.1     1017           10.8   
6370             0.2820            -0.2820      114.6     1867           13.8   
2879             0.0000             0.0000      641.1      989          254.3   
107              0.0595            -0.0595      875.4      696           38.4   
29               0.0075            -0.0075     9802.0     1103          696.5   

      koi_tce_plnt_num  koi_steff  koi_steff_err1  koi_steff_err2  koi_slogg  \
6122                 1       5737             154            -171      4.327   
6370                 1       5855             158            -175      4.578   
2879                 1       6328             151            -189      4.481   
107                  1       4768              76             -85      4.536   
29                   1       5712              77             -77      4.359   

      koi_slogg_err1  koi_slogg_err2         ra  
6122           0.153          -0.187  294.40472  
6370           0.033          -0.187  284.50391  
2879           0.050          -0.200  295.50211  
107            0.056          -0.016  291.15878  
29             0.110          -0.110  292.16705

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [10]:
from tensorflow import keras

In [11]:
# Scale your data
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

#Use MinMaxScaler to Scale Data Points to Range (0,1) and Transform to Center and Scale the Data
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
print(f"X_train_scaled: {X_train_scaled}")
print(f"X_test_scaled: {X_test_scaled}")
print(f"X_train_scaled shape: {X_train_scaled.shape}")
print(f"X_test_scaled shape: {X_test_scaled.shape}")

#Use One Hot Encoding to Convert the KOI Disposition Values to Integers
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)
print(f"encoded_y_train: {y_train}")
print(f"encoded_y_test: {y_test}")
print(f"encoded_y_train shape: {y_train.shape}")
print(f"encoded_y_test shape: {y_test.shape}")
#Convert the Encoded Values into One Hot Values
one_hot_y_train = to_categorical(encoded_y_train)
one_hot_y_test = to_categorical(encoded_y_test)
print(f"one_hot_y_train: {one_hot_y_train}")
print(f"one_hot_y_test: {one_hot_y_test}")
print(f"one_hot_y_train shape: {one_hot_y_train.shape}")
print(f"one_hot_y_test shape: {one_hot_y_test.shape}")

X_train_scaled: [[0.         0.         0.         ... 0.10394022 0.76970443 0.66574567]
 [0.         1.         0.         ... 0.02241848 0.76970443 0.21268467]
 [1.         0.         0.         ... 0.03396739 0.75369458 0.71596223]
 ...
 [0.         1.         0.         ... 0.18342391 0.77832512 0.792823  ]
 [1.         0.         0.         ... 0.19904891 0.87931034 0.77821733]
 [0.         0.         1.         ... 0.04891304 0.79310345 0.68082222]]
X_test_scaled: [[1.         0.         0.         ... 0.04076087 0.9137931  0.71935671]
 [0.         0.         0.         ... 0.01630435 0.85591133 0.81490723]
 [0.         0.         1.         ... 0.0326087  0.90394089 0.52590633]
 ...
 [0.         0.         0.         ... 0.05163043 0.88546798 0.69767242]
 [0.         0.         0.         ... 0.13586957 0.77832512 0.67275473]
 [0.         0.         0.         ... 0.06182065 0.95197044 0.56882006]]
X_train_scaled shape: (5243, 17)
X_test_scaled shape: (1748, 17)
encoded_y_train:

C:\Users\bjros\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\bjros\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
#Create a Sequential Model
from tensorflow.keras.models import Sequential

model2 = Sequential()
model2

In [13]:
#Add Layer for the Number of Inputs and Processing Nodes in the Hidden Layer
from tensorflow.keras.layers import Dense
number_inputs = 17
number_hidden_nodes = 4
model2.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))

In [14]:
#Add Layer for the Outputs and Activation Function
number_classes = 3
model2.add(Dense(units=number_classes, activation='softmax'))

# Train the Model



In [15]:
#Create a Model Summary
model2.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 72        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 87
Trainable params: 87
Non-trainable params: 0
_________________________________________________________________


In [16]:
#Compile the Model
#Loss is categorical_crossentropy, because it is categorical data
#Metrics is Accuracy, because it is desired to assess the accuracy of this model in predicting correct planet classifications
model2.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
#one_hot_reshape = one_hot_y_train.reshape(-1, 1)
#print(f"one_hot_y_train shape: {one_hot_reshape}")

In [18]:
#Train the Model
#Epochs=1000 chosen to Allow Enough Iterations to Minimize Losss and Improve Accuracy
#shuffle=True chosen to shuffle the Training Data
#verbose=2, because it is desired to see how the Loss and Accuracy Change Across Epochs
model2.fit(X_train_scaled, one_hot_y_train, epochs=1000, shuffle=True, verbose=2)

Train on 5243 samples
Epoch 1/1000
5243/5243 - 1s - loss: 1.0172 - accuracy: 0.3845
Epoch 2/1000
5243/5243 - 0s - loss: 0.8134 - accuracy: 0.5964
Epoch 3/1000
5243/5243 - 0s - loss: 0.6834 - accuracy: 0.7150
Epoch 4/1000
5243/5243 - 0s - loss: 0.5726 - accuracy: 0.7461
Epoch 5/1000
5243/5243 - 0s - loss: 0.4984 - accuracy: 0.7675
Epoch 6/1000
5243/5243 - 0s - loss: 0.4532 - accuracy: 0.7850
Epoch 7/1000
5243/5243 - 0s - loss: 0.4260 - accuracy: 0.7973
Epoch 8/1000
5243/5243 - 0s - loss: 0.4087 - accuracy: 0.8104
Epoch 9/1000
5243/5243 - 0s - loss: 0.3971 - accuracy: 0.8142
Epoch 10/1000
5243/5243 - 0s - loss: 0.3887 - accuracy: 0.8182
Epoch 11/1000
5243/5243 - 0s - loss: 0.3825 - accuracy: 0.8167
Epoch 12/1000
5243/5243 - 0s - loss: 0.3777 - accuracy: 0.8186
Epoch 13/1000
5243/5243 - 0s - loss: 0.3736 - accuracy: 0.8196
Epoch 14/1000
5243/5243 - 0s - loss: 0.3703 - accuracy: 0.8207
Epoch 15/1000
5243/5243 - 0s - loss: 0.3672 - accuracy: 0.8190
Epoch 16/1000
5243/5243 - 0s - loss: 0.364

Epoch 131/1000
5243/5243 - 0s - loss: 0.2957 - accuracy: 0.8653
Epoch 132/1000
5243/5243 - 0s - loss: 0.2958 - accuracy: 0.8680
Epoch 133/1000
5243/5243 - 0s - loss: 0.2950 - accuracy: 0.8657
Epoch 134/1000
5243/5243 - 0s - loss: 0.2949 - accuracy: 0.8648
Epoch 135/1000
5243/5243 - 0s - loss: 0.2951 - accuracy: 0.8669
Epoch 136/1000
5243/5243 - 0s - loss: 0.2940 - accuracy: 0.8663
Epoch 137/1000
5243/5243 - 0s - loss: 0.2946 - accuracy: 0.8648
Epoch 138/1000
5243/5243 - 0s - loss: 0.2942 - accuracy: 0.8655
Epoch 139/1000
5243/5243 - 0s - loss: 0.2942 - accuracy: 0.8673
Epoch 140/1000
5243/5243 - 0s - loss: 0.2942 - accuracy: 0.8665
Epoch 141/1000
5243/5243 - 0s - loss: 0.2941 - accuracy: 0.8646
Epoch 142/1000
5243/5243 - 0s - loss: 0.2940 - accuracy: 0.8682
Epoch 143/1000
5243/5243 - 0s - loss: 0.2948 - accuracy: 0.8650
Epoch 144/1000
5243/5243 - 0s - loss: 0.2929 - accuracy: 0.8661
Epoch 145/1000
5243/5243 - 0s - loss: 0.2929 - accuracy: 0.8663
Epoch 146/1000
5243/5243 - 0s - loss: 0.

5243/5243 - 0s - loss: 0.2880 - accuracy: 0.8699
Epoch 260/1000
5243/5243 - 0s - loss: 0.2883 - accuracy: 0.8703
Epoch 261/1000
5243/5243 - 0s - loss: 0.2879 - accuracy: 0.8699
Epoch 262/1000
5243/5243 - 0s - loss: 0.2872 - accuracy: 0.8705
Epoch 263/1000
5243/5243 - 0s - loss: 0.2885 - accuracy: 0.8699
Epoch 264/1000
5243/5243 - 0s - loss: 0.2882 - accuracy: 0.8722
Epoch 265/1000
5243/5243 - 0s - loss: 0.2875 - accuracy: 0.8682
Epoch 266/1000
5243/5243 - 0s - loss: 0.2878 - accuracy: 0.8693
Epoch 267/1000
5243/5243 - 0s - loss: 0.2874 - accuracy: 0.8726
Epoch 268/1000
5243/5243 - 0s - loss: 0.2883 - accuracy: 0.8688
Epoch 269/1000
5243/5243 - 0s - loss: 0.2880 - accuracy: 0.8713
Epoch 270/1000
5243/5243 - 0s - loss: 0.2873 - accuracy: 0.8718
Epoch 271/1000
5243/5243 - 0s - loss: 0.2877 - accuracy: 0.8703
Epoch 272/1000
5243/5243 - 0s - loss: 0.2882 - accuracy: 0.8699
Epoch 273/1000
5243/5243 - 0s - loss: 0.2882 - accuracy: 0.8711
Epoch 274/1000
5243/5243 - 0s - loss: 0.2873 - accuracy

Epoch 388/1000
5243/5243 - 0s - loss: 0.2862 - accuracy: 0.8737
Epoch 389/1000
5243/5243 - 0s - loss: 0.2867 - accuracy: 0.8684
Epoch 390/1000
5243/5243 - 0s - loss: 0.2871 - accuracy: 0.8728
Epoch 391/1000
5243/5243 - 0s - loss: 0.2873 - accuracy: 0.8711
Epoch 392/1000
5243/5243 - 0s - loss: 0.2864 - accuracy: 0.8688
Epoch 393/1000
5243/5243 - 0s - loss: 0.2873 - accuracy: 0.8684
Epoch 394/1000
5243/5243 - 0s - loss: 0.2870 - accuracy: 0.8714
Epoch 395/1000
5243/5243 - 0s - loss: 0.2869 - accuracy: 0.8714
Epoch 396/1000
5243/5243 - 0s - loss: 0.2862 - accuracy: 0.8709
Epoch 397/1000
5243/5243 - 0s - loss: 0.2871 - accuracy: 0.8697
Epoch 398/1000
5243/5243 - 0s - loss: 0.2868 - accuracy: 0.8703
Epoch 399/1000
5243/5243 - 0s - loss: 0.2861 - accuracy: 0.8720
Epoch 400/1000
5243/5243 - 0s - loss: 0.2864 - accuracy: 0.8718
Epoch 401/1000
5243/5243 - 0s - loss: 0.2870 - accuracy: 0.8726
Epoch 402/1000
5243/5243 - 0s - loss: 0.2866 - accuracy: 0.8713
Epoch 403/1000
5243/5243 - 0s - loss: 0.

5243/5243 - 0s - loss: 0.2867 - accuracy: 0.8713
Epoch 517/1000
5243/5243 - 0s - loss: 0.2855 - accuracy: 0.8737
Epoch 518/1000
5243/5243 - 0s - loss: 0.2864 - accuracy: 0.8693
Epoch 519/1000
5243/5243 - 0s - loss: 0.2862 - accuracy: 0.8703
Epoch 520/1000
5243/5243 - 0s - loss: 0.2858 - accuracy: 0.8682
Epoch 521/1000
5243/5243 - 0s - loss: 0.2861 - accuracy: 0.8695
Epoch 522/1000
5243/5243 - 0s - loss: 0.2864 - accuracy: 0.8730
Epoch 523/1000
5243/5243 - 0s - loss: 0.2866 - accuracy: 0.8701
Epoch 524/1000
5243/5243 - 0s - loss: 0.2858 - accuracy: 0.8737
Epoch 525/1000
5243/5243 - 0s - loss: 0.2859 - accuracy: 0.8684
Epoch 526/1000
5243/5243 - 0s - loss: 0.2864 - accuracy: 0.8709
Epoch 527/1000
5243/5243 - 0s - loss: 0.2868 - accuracy: 0.8716
Epoch 528/1000
5243/5243 - 0s - loss: 0.2857 - accuracy: 0.8716
Epoch 529/1000
5243/5243 - 0s - loss: 0.2867 - accuracy: 0.8686
Epoch 530/1000
5243/5243 - 0s - loss: 0.2861 - accuracy: 0.8722
Epoch 531/1000
5243/5243 - 0s - loss: 0.2864 - accuracy

Epoch 645/1000
5243/5243 - 0s - loss: 0.2855 - accuracy: 0.8705
Epoch 646/1000
5243/5243 - 0s - loss: 0.2853 - accuracy: 0.8697
Epoch 647/1000
5243/5243 - 0s - loss: 0.2856 - accuracy: 0.8709
Epoch 648/1000
5243/5243 - 0s - loss: 0.2860 - accuracy: 0.8711
Epoch 649/1000
5243/5243 - 0s - loss: 0.2860 - accuracy: 0.8703
Epoch 650/1000
5243/5243 - 0s - loss: 0.2853 - accuracy: 0.8734
Epoch 651/1000
5243/5243 - 0s - loss: 0.2857 - accuracy: 0.8697
Epoch 652/1000
5243/5243 - 0s - loss: 0.2859 - accuracy: 0.8703
Epoch 653/1000
5243/5243 - 0s - loss: 0.2854 - accuracy: 0.8699
Epoch 654/1000
5243/5243 - 0s - loss: 0.2850 - accuracy: 0.8709
Epoch 655/1000
5243/5243 - 0s - loss: 0.2855 - accuracy: 0.8707
Epoch 656/1000
5243/5243 - 0s - loss: 0.2858 - accuracy: 0.8703
Epoch 657/1000
5243/5243 - 0s - loss: 0.2856 - accuracy: 0.8747
Epoch 658/1000
5243/5243 - 0s - loss: 0.2858 - accuracy: 0.8709
Epoch 659/1000
5243/5243 - 0s - loss: 0.2858 - accuracy: 0.8728
Epoch 660/1000
5243/5243 - 0s - loss: 0.

5243/5243 - 0s - loss: 0.2848 - accuracy: 0.8737
Epoch 774/1000
5243/5243 - 0s - loss: 0.2854 - accuracy: 0.8695
Epoch 775/1000
5243/5243 - 0s - loss: 0.2857 - accuracy: 0.8707
Epoch 776/1000
5243/5243 - 0s - loss: 0.2852 - accuracy: 0.8697
Epoch 777/1000
5243/5243 - 0s - loss: 0.2857 - accuracy: 0.8673
Epoch 778/1000
5243/5243 - 0s - loss: 0.2850 - accuracy: 0.8714
Epoch 779/1000
5243/5243 - 0s - loss: 0.2855 - accuracy: 0.8735
Epoch 780/1000
5243/5243 - 0s - loss: 0.2856 - accuracy: 0.8709
Epoch 781/1000
5243/5243 - 0s - loss: 0.2856 - accuracy: 0.8695
Epoch 782/1000
5243/5243 - 0s - loss: 0.2855 - accuracy: 0.8697
Epoch 783/1000
5243/5243 - 0s - loss: 0.2854 - accuracy: 0.8692
Epoch 784/1000
5243/5243 - 0s - loss: 0.2845 - accuracy: 0.8722
Epoch 785/1000
5243/5243 - 0s - loss: 0.2857 - accuracy: 0.8705
Epoch 786/1000
5243/5243 - 0s - loss: 0.2853 - accuracy: 0.8726
Epoch 787/1000
5243/5243 - 0s - loss: 0.2869 - accuracy: 0.8699
Epoch 788/1000
5243/5243 - 0s - loss: 0.2848 - accuracy

Epoch 902/1000
5243/5243 - 0s - loss: 0.2859 - accuracy: 0.8718
Epoch 903/1000
5243/5243 - 0s - loss: 0.2854 - accuracy: 0.8711
Epoch 904/1000
5243/5243 - 0s - loss: 0.2851 - accuracy: 0.8688
Epoch 905/1000
5243/5243 - 0s - loss: 0.2857 - accuracy: 0.8713
Epoch 906/1000
5243/5243 - 0s - loss: 0.2851 - accuracy: 0.8713
Epoch 907/1000
5243/5243 - 0s - loss: 0.2852 - accuracy: 0.8728
Epoch 908/1000
5243/5243 - 0s - loss: 0.2846 - accuracy: 0.8707
Epoch 909/1000
5243/5243 - 0s - loss: 0.2858 - accuracy: 0.8709
Epoch 910/1000
5243/5243 - 0s - loss: 0.2852 - accuracy: 0.8722
Epoch 911/1000
5243/5243 - 0s - loss: 0.2859 - accuracy: 0.8701
Epoch 912/1000
5243/5243 - 0s - loss: 0.2857 - accuracy: 0.8711
Epoch 913/1000
5243/5243 - 0s - loss: 0.2849 - accuracy: 0.8709
Epoch 914/1000
5243/5243 - 0s - loss: 0.2859 - accuracy: 0.8707
Epoch 915/1000
5243/5243 - 0s - loss: 0.2851 - accuracy: 0.8753
Epoch 916/1000
5243/5243 - 0s - loss: 0.2848 - accuracy: 0.8705
Epoch 917/1000
5243/5243 - 0s - loss: 0.

In [27]:
#Evaluate the Model Using the Testing Data
model_loss, model_accuracy = model2.evaluate(X_test_scaled, one_hot_y_test, verbose=2)
print(f"Model Loss: {model_loss}")
print(f"Model Accuracy: {model_accuracy}")

1748/1748 - 0s - loss: 0.2979 - accuracy: 0.8701
Model Loss: 0.297923514512911
Model Accuracy: 0.8701372742652893


# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [28]:
# Create the GridSearchCV model along with a parameter object containing the values to adjust
#Different C values were tested to try to best classify all the data without overfitting
#Different Gamma values were tested to try to optimize the nearness of data points with respect to the plausible line of separation
#Info Found at https://towardsdatascience.com/svm-hyper-parameter-tuning-using-gridsearchcv-49c0bc55ce29
from sklearn.model_selection import GridSearchCV
# Support vector machine linear classifier
from sklearn.svm import SVC
grid_model = SVC(kernel='linear')
param_grid = {'C': [1, 5, 10],
              'gamma': [0.0001, 0.001, 0.01]}
grid2 = GridSearchCV(grid_model, param_grid, verbose=3, scoring='accuracy')

In [29]:
# Train the model with GridSearch
# This will take the SVC model and try each combination of parameters
grid2.fit(X_train_scaled, encoded_y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.842, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ................... C=1, gamma=0.0001, score=0.824, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.842, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.1s remaining:    0.0s


[CV] ................... C=1, gamma=0.0001, score=0.817, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.818, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.842, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.824, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.842, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.817, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.818, total=   0.1s
[CV] C=1, gamma=0.01 .................................................
[CV] .

[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed:    5.7s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 5, 10], 'gamma': [0.0001, 0.001, 0.01]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=3)

In [30]:
print(grid2.best_params_)
print(grid2.best_score_)

{'C': 10, 'gamma': 0.0001}
0.8498908447885662


In [31]:
# Make predictions with the hypertuned model
predictions = grid2.predict(X_test_scaled)

In [32]:
# Calculate classification report
#Accuracy = (True Positives + True Negatives)/(All Observations)
#Precision = (True Positives)/(True Positives + False Positives)
#Recall = (True Positives)/(True Positives + False Negatives)
#F1 Score = 2 * (Precision * Recall)/(Precision + Recall)
from sklearn.metrics import classification_report
print(classification_report(encoded_y_test, predictions,
                            target_names=["CONFIRMED", "FALSE POSITIVE", "CANDIDATE"]))

                precision    recall  f1-score   support

     CONFIRMED       0.70      0.65      0.68       411
FALSE POSITIVE       0.73      0.75      0.74       484
     CANDIDATE       0.98      1.00      0.99       853

      accuracy                           0.85      1748
     macro avg       0.80      0.80      0.80      1748
  weighted avg       0.84      0.85      0.85      1748



In [33]:
#Run F Classification (Compute ANOVA F-Value for the Provided Features and Only Consider the Most Important Features)
#ANOVA is a ratio of the Variation Between Samples and the Sum of Variation within Each Sample
#Method Found at https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.f_classif.html#sklearn.feature_selection.f_classif
import sklearn

ANOVA_results = sklearn.feature_selection.f_classif(X_train_scaled, encoded_y_train)
#print(f"The selected features are: {selected_features.columns.values}")
#print(f"The F-values are: {ANOVA_results[0]}")
#print(f"The p-values are: {ANOVA_results[1]}")
F_classification_DF = pd.DataFrame({'Selected Features': selected_features.columns.values, 'F-values': ANOVA_results[0], 'p-values': ANOVA_results[1]})
F_classification_DF.sort_values('F-values', ascending=False)

Selected Features     F-values       p-values
1       koi_fpflag_ss  1057.420634   0.000000e+00
2       koi_fpflag_co   865.908600   0.000000e+00
0       koi_fpflag_nt   558.543756  1.292749e-220
11     koi_steff_err1   533.036760  1.902453e-211
3       koi_fpflag_ec   429.776495  1.469566e-173
12     koi_steff_err2   429.268196  2.274301e-173
6           koi_depth   210.190929   1.556533e-88
7             koi_teq   207.358855   2.144554e-87
15     koi_slogg_err2   185.617922   1.302093e-78
8       koi_model_snr   179.986327   2.517083e-76
9    koi_tce_plnt_num   128.486671   3.342407e-55
10          koi_steff   108.518577   6.620121e-47
5   koi_duration_err2    85.831320   2.096517e-37
4   koi_duration_err1    85.831320   2.096517e-37
16                 ra    79.234210   1.256294e-34
14     koi_slogg_err1    67.788935   8.591310e-30
13          koi_slogg    66.399917   3.328433e-29

# Save the Model

In [34]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'ben_roseburrough.sav'
joblib.dump(grid_model, filename)
#model2.save(filename)

['ben_roseburrough.sav']